services:
  postgres:
    image: postgres:16-alpine
    container_name: task-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5440:5432"
    volumes:
      -  task_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: task-service
    restart: unless-stopped
    ports:
      - "8084:8084"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SSL_MODE: disable
      SPRING_PROFILES_ACTIVE: postgres,feign
      ACADEMIC_SERVICE_URL: ${ACADEMIC_SERVICE_URL:-http://localhost:8083}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  task_db_data:
